### ISSUE TITLE
NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [Kaesebrot84/iris#8]
Hi,

I've just packaged `cliris` for NetBSD.
I'm planning to merge it into our repositories this evening or, possibly tomorrow, depends on available time.

Would you mind hosting `Cargo.lock` in the repository, simply remove it from `.gitignore`?
We have a script that reads `Cargo.lock` and generates a list of dependency crates. When the file is hidden, I need to do this manually.

Thanks!

**Edit:** [merged](https://mail-index.netbsd.org/pkgsrc-changes/2022/08/31/msg259648.html)

**Comment by Kaesebrot84** [comment]
@0323pin Sorry for the slow response, I just lost `Cargo.lock` in `.gitignore`, see [here](https://github.com/Kaesebrot84/iris/commit/cc4167e93699c8091b48ed65cb4947c394915b00).

Regards

**Comment by 0323pin** [comment]
@Kaesebrot84 Cheers.
